### ISSUE TITLE
Not a valid truetype font (openhtmltopdf)

### ISSUE THREAD

**Issue by elfwine** [hiz8/Noto-Serif-CJK-JP.min#1]
I tried to use this font for openhtmltopdf but when I load the .ttf fonts, it got me an error of not a valid truetype font.
I couldn't find any NotoSerifCJKjp truetype font (.ttf), most of the available fonts are in .otf format.

Any chance to validate the ttf file?

Thanks and regards,

**Comment by hiz8** [comment]
Hmm, for my use, this file seems to work fine.
I'm not familiar with openhtmltopdf, but maybe it's a compatibility issue.

[The software I'm using for subsetting](https://opentype.jp/subsetfontmk.htm) seems to target the web, so it's possible that some data needed for openhtmltopdf is lost during the conversion.

**Comment by elfwine** [comment]
Thank you for your reply. 
I also tried to use it with Apache pdfbox, and it also throws an invalid truetype font error. 
I ended up using IPA Mincho (ipaexm.ttf) and another latin font as IPA font didn't give me an error.
It would be great to use Noto-Serif JP though.

Thanks.
